import { authedUrl, req, reqRaw } from './api/http'
import type { AddonStatus, ApiToken, AuditEntry, Build, CertInfo, ClusterForm, ClusterRow, ClusterSpec, FluxObject, FluxRepository, HealthEvent, ImageStatus, Inventory, LabLocal, LabUpdates, MaintenanceState, Me, Namespace, NetworkView, NodeDetail, NodeNetwork, NodeRow, NodeSpec, OOBConfig, OOBInfo, ObserverState, OffsiteStatus, OffsiteTarget, OpRef, Operation, PodEvent, PodSummary, Pool, PxeStatus, Role, SOPSKey, Sample, Service, ServiceHealth, Settings, Snapshot, Status, StorageView, User, VMPlan, Versions, Warning, Workload } from './api/types'

export type * from './api/types'
export { authedUrl, getToken, setUnauthorizedHandler } from './api/http'
export { fmt, splitList } from './api/format'

export const api = {
  me: () => req<Me>('GET', '/auth/me'),
  login: (name: string, password: string) => req<Me>('POST', '/auth/login', { name, password }),
  setup: (name: string, password: string) => req<Me>('POST', '/auth/setup', { name, password }),
  logout: () => req<void>('POST', '/auth/logout'),
  users: () => req<User[]>('GET', '/users'),
  createUser: (name: string, password: string, role: Role) => req<User>('POST', '/users', { name, password, role }),
  updateUser: (name: string, patch: { role?: Role; disabled?: boolean; password?: string }) => req<User>('PUT', `/users/${name}`, patch),
  deleteUser: (name: string) => req<void>('DELETE', `/users/${name}`),
  tokens: (user: string) => req<ApiToken[]>('GET', `/users/${user}/tokens`),
  createToken: (user: string, name: string, days: number) => req<{ token: string }>('POST', `/users/${user}/tokens`, { name, days }),
  deleteToken: (user: string, name: string) => req<void>('DELETE', `/users/${user}/tokens/${encodeURIComponent(name)}`),
  observer: () => req<ObserverState>('GET', '/observer'),
  clusters: () => req<ClusterRow[]>('GET', '/clusters'),
  status: (name: string, fresh = false) => req<Status>('GET', `/clusters/${name}/status${fresh ? '?fresh=true' : ''}`),
  samples: (name: string, range = '24h', node = '') => req<Sample[]>('GET', `/clusters/${name}/samples?range=${range}&node=${encodeURIComponent(node)}`),
  events: (name: string, unacked = false) => req<HealthEvent[]>('GET', `/clusters/${name}/events?limit=200&unacked=${unacked}`),
  ackEvent: (id: number) => req<void>('POST', `/events/${id}/ack`),
  ackAll: (name: string) => req<void>('POST', `/clusters/${name}/events/ack`),
  versions: () => req<Versions>('GET', '/versions'),
  saveClusterForm: (name: string, form: ClusterForm) => req<{ yaml: string }>('PUT', `/clusters/${name}/form`, form),
  settings: () => req<Settings>('GET', '/settings'),
  serviceHealth: (name: string) => req<{ latest: ServiceHealth | null; alerts: HealthEvent[] }>('GET', `/clusters/${name}/service-health`),
  retireMachine: (mac: string) => req<void>('DELETE', `/machines/${mac}`),
  setWOL: (mac: string, enabled: boolean) => req<void>('PUT', `/machines/${mac}/wol`, { enabled }),
  wake: (mac: string) => req<void>('POST', `/machines/${mac}/wake`),
  saveOOB: (mac: string, c: OOBConfig) => req<void>('PUT', `/machines/${mac}/oob`, c),
  oobTest: (mac: string, c?: OOBConfig) => req<{ ok: boolean; error?: string; info?: OOBInfo }>('POST', `/machines/${mac}/oob/test`, c ?? {}),
  power: (mac: string, action: 'on' | 'off' | 'reset' | 'cycle' | 'pxe') => req<OpRef>('POST', `/machines/${mac}/power`, { action }),
  addOOBMachine: (c: OOBConfig) => req<{ machine: NodeRow; info: OOBInfo }>('POST', '/machines/oob', c),
  labProvision: (mac: string, plan?: { manual?: boolean; network?: 'bridge' | 'routed'; disk?: string; vms?: VMPlan; cluster?: { name: string; controlPlanes: 1 | 3; skipPlatform?: boolean; repository?: FluxRepository } }) => req<OpRef>('POST', `/machines/${mac}/labhost`, plan ?? {}),
  labRelease: (mac: string) => req<{ warning?: string } | undefined>('DELETE', `/machines/${mac}/labhost`),
  labLocal: () => req<LabLocal>('GET', '/labhosts/local'),
  labLocalCreate: (plan: { vms?: VMPlan; cluster?: { name: string; controlPlanes: 1 | 3; skipPlatform?: boolean; repository?: FluxRepository } }) => req<OpRef & { mac: string }>('POST', '/labhosts', { driver: 'vfkit', ...plan }),
  labSamples: (mac: string, range: string) => req<Sample[]>('GET', `/machines/${mac}/labhost/samples?range=${range}`),
  labCheck: (mac: string) => req<LabUpdates>('POST', `/machines/${mac}/labhost/check`),
  labUpdate: (mac: string) => req<OpRef>('POST', `/machines/${mac}/labhost/update?ignoreWindow=true`),
  labReboot: (mac: string) => req<OpRef>('POST', `/machines/${mac}/labhost/reboot?ignoreWindow=true`),
  labAddVMs: (mac: string, r: VMPlan) => req<OpRef>('POST', `/machines/${mac}/labhost/vms`, r),
  labVM: (mac: string, name: string, action: 'start' | 'stop' | 'kill' | 'reprovision') => req<OpRef>('POST', `/machines/${mac}/labhost/vms/${name}/${action}`),
  labVMResize: (mac: string, name: string, cpus: number, memMiB: number) => req<void>('PUT', `/machines/${mac}/labhost/vms/${name}`, { cpus, memMiB }),
  labVMDelete: (mac: string, name: string) => req<void>('DELETE', `/machines/${mac}/labhost/vms/${name}`),
  design: (name: string, macs: string[], metallbRange?: string) => req<{ yaml: string; cluster: ClusterSpec; warnings: Warning[]; topology: { ControlPlanes: number; Workers: number; AllowScheduling: boolean; HA: boolean }; overlaps?: string[] }>('POST', '/config/design', { name, macs, metallbRange }),
  lint: (yaml: string) => req<{ warnings: Warning[]; yaml: string }>('POST', '/config/lint', { yaml }),
  renameNode: (cluster: string, hostname: string, to: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/rename?ignoreWindow=true`, { to }),
  moveNodePool: (cluster: string, hostname: string, pool: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/pool?ignoreWindow=true`, { pool }),
  readdressNode: (cluster: string, hostname: string, network: NodeNetwork | null, ip: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/readdress?ignoreWindow=true`, { network, ip }),
  certificates: (cluster: string) => req<CertInfo[]>('GET', `/clusters/${cluster}/certificates`),
  rotateCredential: (cluster: string, which: 'talosconfig' | 'kubeconfig') => req<OpRef>('POST', `/clusters/${cluster}/certificates/rotate`, { which }),
  maintenance: (cluster: string) => req<MaintenanceState>('GET', `/clusters/${cluster}/maintenance`),
  audit: (cluster?: string) => req<AuditEntry[]>('GET', '/audit' + (cluster ? `?cluster=${cluster}` : '')),
  testAlerts: () => req<{ ok: boolean; errors: string[] }>('POST', '/settings/alerts/test'),
  offsiteStatus: () => req<OffsiteStatus>('GET', '/settings/offsite'),
  offsiteTest: (t: OffsiteTarget) => req<{ ok: boolean; error?: string; roundTripMs?: number; target?: string }>('POST', '/settings/offsite/test', t),
  offsiteBackup: () => req<OpRef>('POST', '/settings/offsite/backup'),
  snapshots: (cluster: string) => req<Snapshot[]>('GET', `/clusters/${cluster}/snapshots`),
  takeSnapshot: (cluster: string) => req<OpRef>('POST', `/clusters/${cluster}/snapshots`, { source: 'manual' }),
  deleteSnapshot: (cluster: string, id: number) => req<void>('DELETE', `/clusters/${cluster}/snapshots/${id}`),
  verifySnapshot: (cluster: string, id: number) => req<{ ok: boolean; error?: string; snapshot: Snapshot }>('POST', `/clusters/${cluster}/snapshots/${id}/verify`),
  restoreSnapshot: (cluster: string, id: number) => req<OpRef>('POST', `/clusters/${cluster}/snapshots/${id}/restore?ignoreWindow=true`, { confirm: cluster }),
  savePools: (cluster: string, pools: Pool[]) => req<Pool[]>('PUT', `/clusters/${cluster}/pools`, pools),
  saveSettings: (v: Settings) => req<Settings>('PUT', '/settings', v),
  pxe: () => req<PxeStatus>('GET', '/pxe'),
  addons: (name: string) => req<AddonStatus[]>('GET', `/clusters/${name}/addons`),
  updateAddon: (name: string, key: string, body: { enabled?: boolean; range?: string; valuesYaml?: string; repository?: FluxRepository }) => req<AddonStatus[]>('PUT', `/clusters/${name}/addons/${key}`, body),
  workloads: (name: string) => req<Workload[]>('GET', `/clusters/${name}/workloads`),
  namespaces: (name: string) => req<Namespace[]>('GET', `/clusters/${name}/namespaces`),
  imageStatus: (name: string) => req<ImageStatus>('GET', `/clusters/${name}/image`),
  sopsKey: (name: string) => req<SOPSKey>('GET', `/clusters/${name}/sops`),
  flux: (name: string) => req<FluxObject[]>('GET', `/clusters/${name}/flux`),
  builds: (name: string) => req<Build[]>('GET', `/clusters/${name}/builds`),
  importSOPSKey: (name: string, keys: string) => req<SOPSKey>('PUT', `/clusters/${name}/sops/identity`, { keys }),
  pods: (name: string, namespace = '', selector = '') => req<PodSummary[]>('GET', `/clusters/${name}/pods?namespace=${encodeURIComponent(namespace)}&selector=${encodeURIComponent(selector)}`),
  podEvents: (name: string, ns: string, pod: string) => req<PodEvent[]>('GET', `/clusters/${name}/pods/${ns}/${pod}/events`),
  network: (name: string) => req<NetworkView>('GET', `/clusters/${name}/network`),
  storage: (name: string) => req<StorageView>('GET', `/clusters/${name}/storage`),
  clusterYaml: (name: string) => req<string>('GET', `/clusters/${name}/yaml`),
  saveClusterYaml: (name: string, yaml: string) => reqRaw<{ yaml: string }>('PUT', `/clusters/${name}/yaml`, yaml),
  createCluster: (yaml: string, skipPlatform = false) => req<OpRef & { cluster: string }>('POST', '/clusters', { yaml, skipPlatform }),
  forgetCluster: (name: string, deleteVMs = false) => req<void>('DELETE', `/clusters/${name}${deleteVMs ? '?vms=delete' : ''}`),
  applyCluster: (name: string, yaml?: string) => req<OpRef>('POST', `/clusters/${name}/apply?ignoreWindow=true`, { yaml: yaml || '' }),
  platformPlan: (name: string) => req<OpRef>('POST', `/clusters/${name}/platform/plan`),
  platformApplyPlan: (name: string, planId: number) => req<OpRef>('POST', `/clusters/${name}/platform/apply/${planId}`),
  upgradeTalos: (name: string, to: string) => req<OpRef>('POST', `/clusters/${name}/upgrade/talos?ignoreWindow=true`, { to }),
  upgradeKubernetes: (name: string, to: string) => req<OpRef>('POST', `/clusters/${name}/upgrade/kubernetes?ignoreWindow=true`, { to }),
  exportCluster: (name: string, dir?: string) => req<{ dir: string }>('POST', `/clusters/${name}/export`, { dir: dir || '' }),
  addNode: (name: string, node: NodeSpec) => req<OpRef>('POST', `/clusters/${name}/nodes`, node),
  removeNode: (name: string, hostname: string, force = false) => req<OpRef>('DELETE', `/clusters/${name}/nodes/${hostname}?force=${force}&ignoreWindow=true`),
  nodes: (cluster?: string) => req<NodeRow[]>('GET', '/nodes' + (cluster ? `?cluster=${cluster}` : '')),
  discover: (targets: string[]) => req<OpRef>('POST', '/discover', { targets }),
  services: (ip: string) => req<Service[]>('GET', `/nodes/${ip}/services`),
  inventory: (ip: string) => req<Inventory>('GET', `/nodes/${ip}/inventory`),
  nodeKubernetes: (ip: string) => req<NodeDetail>('GET', `/nodes/${ip}/kubernetes`),
  cordon: (cluster: string, hostname: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/cordon`),
  uncordon: (cluster: string, hostname: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/uncordon`),
  drain: (cluster: string, hostname: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/drain?ignoreWindow=true`),
  rebootNode: (cluster: string, hostname: string, drain: boolean) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/reboot?ignoreWindow=true`, { drain }),
  upgradeNode: (cluster: string, hostname: string, to: string) => req<OpRef>('POST', `/clusters/${cluster}/nodes/${hostname}/upgrade?ignoreWindow=true`, { to }),
  operations: () => req<Operation[]>('GET', '/operations'),
  operation: (id: number) => req<Operation>('GET', `/operations/${id}`),
  cancelOperation: (id: number) => req<void>('DELETE', `/operations/${id}`),
  retryOperation: (id: number) => req<OpRef>('POST', `/operations/${id}/retry`),
  validate: (yaml: string) => reqRaw<{ yaml: string; cluster: ClusterSpec }>('POST', '/config/validate', yaml),
}

export function podLogsUrl(cluster: string, ns: string, pod: string, container: string, follow: boolean, tail = 500) {
  const p = new URLSearchParams({ container, tail: String(tail) })
  if (follow) p.set('follow', 'true')
  return authedUrl(`/clusters/${cluster}/pods/${ns}/${pod}/logs`, p)
}

export function logsUrl(ip: string, service?: string, follow = false) {
  const p = new URLSearchParams()
  if (service) p.set('service', service)
  if (follow) p.set('follow', 'true')
  return authedUrl(`/nodes/${ip}/logs`, p)
}
